### ISSUE TITLE
Can't pip install this git repository

### ISSUE THREAD

**Issue by XiangYang95** [palto42/simple_scheduler#1]
I'm on Windows so I tried doing "pip install -e git+https://github.com/palto42/simple_scheduler.git#egg=simple_scheduler" in my Anaconda prompt. But it doesn't work as it gave me the following error:
![Screenshot_1](https://user-images.githubusercontent.com/36871829/192209971-0cb7f3aa-8a7a-4ed9-b7ff-b03531a31ba8.png)
Any solution for this?

**Comment by palto42** [comment]
Hi @XiangYang95 , I checked your issue and found that it was caused by and inconsistent package renaming of my fork for [ndscheduler](https://github.com/palto42/ndscheduler). I reverted that change and the installation should now work.
